/**
 * TypeScript client for the inference-market Anchor program.
 *
 * Usage (React):
 *   const { postJob, onJobCompleted } = useInferenceMarket();
 *   const result = await postJob({ model: "llama-3.2-3b", prompt: "...", maxTokens: 512 });
 */

import { AnchorProvider, BN, Program, web3 } from "@coral-xyz/anchor";
import { PublicKey, SystemProgram } from "@solana/web3.js";
import { TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID, getAssociatedTokenAddress } from "@solana/spl-token";
import { INFERENCE_MARKET_PROGRAM_ID, MODEL_IDS } from "./sdk";

// IDL is generated by `anchor build` → target/idl/inference_market.json
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type InferenceMarketProgram = Program<any>;

export interface PostJobParams {
  model: keyof typeof MODEL_IDS;
  promptHash: Uint8Array;   // SHA-256 of the plaintext prompt
  maxTokens?: number;
  paymentAmount: bigint;    // in base token units
  deadlineSeconds?: number;
}

export interface CompletionResult {
  jobId: bigint;
  nodePayment: bigint;
  resultCid: string;
  node: string;
}

export interface JobPostedEvent {
  jobId: BN;
  client: PublicKey;
  modelId: number[];
  paymentAmount: BN;
  deadline: BN;
}

export interface JobCompletedEvent {
  jobId: BN;
  node: PublicKey;
  nodePayment: BN;
  protocolFee: BN;
}

export class InferenceMarketClient {
  private program: InferenceMarketProgram;
  private provider: AnchorProvider;

  constructor(provider: AnchorProvider, idl: object) {
    this.provider = provider;
    this.program = new Program(idl as never, INFERENCE_MARKET_PROGRAM_ID, provider);
  }

  /**
   * Post an inference job on-chain and wait for it to be completed.
   * The prompt itself is delivered off-chain (encrypted) to the node.
   */
  async postJob(params: PostJobParams): Promise<CompletionResult> {
    const { model, promptHash, maxTokens = 512, paymentAmount, deadlineSeconds = 120 } = params;

    const modelId = MODEL_IDS[model];
    if (!modelId) throw new Error(`Unknown model: ${model}`);

    const [marketPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("market")],
      INFERENCE_MARKET_PROGRAM_ID
    );

    const market = await this.program.account["market"].fetch(marketPda);
    const jobId: BN = market.totalJobs as BN;

    const [jobPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("job"), jobId.toArrayLike(Buffer, "le", 8)],
      INFERENCE_MARKET_PROGRAM_ID
    );

    const tokenMint = new PublicKey(market.tokenMint as string);
    const clientAta = await getAssociatedTokenAddress(tokenMint, this.provider.wallet.publicKey);
    const escrowAta = await getAssociatedTokenAddress(tokenMint, jobPda, true);

    const deadline = Math.floor(Date.now() / 1000) + deadlineSeconds;

    const tx = await this.program.methods
      .postJob(
        Array.from(modelId),
        Array.from(promptHash),
        maxTokens,
        new BN(paymentAmount.toString()),
        new BN(deadline)
      )
      .accounts({
        market: marketPda,
        job: jobPda,
        escrowTokenAccount: escrowAta,
        clientTokenAccount: clientAta,
        tokenMint,
        client: this.provider.wallet.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    console.log(`Job ${jobId} posted (tx: ${tx})`);

    return this._waitForCompletion(jobId, jobPda, deadline);
  }

  /** Accept a completed result and release payment to the node. */
  async acceptResult(jobId: BN): Promise<string> {
    const [jobPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("job"), jobId.toArrayLike(Buffer, "le", 8)],
      INFERENCE_MARKET_PROGRAM_ID
    );

    const tx = await this.program.methods
      .acceptResult()
      .accounts({ job: jobPda, client: this.provider.wallet.publicKey })
      .rpc();

    return tx;
  }

  /** Subscribe to JobCompleted events for a specific job. */
  onJobCompleted(
    jobId: BN,
    callback: (event: JobCompletedEvent) => void
  ): number {
    return this.program.addEventListener("JobCompleted", (event: JobCompletedEvent) => {
      if ((event.jobId as BN).eq(jobId)) {
        callback(event);
      }
    });
  }

  removeListener(listenerId: number): void {
    this.program.removeEventListener(listenerId);
  }

  // ─────────────────────────── private ─────────────────────────────────────

  private _waitForCompletion(
    jobId: BN,
    jobPda: PublicKey,
    deadline: number
  ): Promise<CompletionResult> {
    return new Promise((resolve, reject) => {
      const listenerId = this.onJobCompleted(jobId, async (event) => {
        this.removeListener(listenerId);
        const job = await this.program.account["job"].fetch(jobPda);
        resolve({
          jobId: BigInt(jobId.toString()),
          nodePayment: BigInt((event.nodePayment as BN).toString()),
          resultCid: job.resultCid as string,
          node: (event.node as PublicKey).toBase58(),
        });
      });

      // Reject if deadline passes without completion
      const msRemaining = (deadline - Date.now() / 1000) * 1000;
      setTimeout(() => {
        this.removeListener(listenerId);
        reject(new Error(`Job ${jobId} timed out after ${msRemaining / 1000}s`));
      }, msRemaining);
    });
  }
}
