"""
Solana interaction layer for compute nodes.

Responsibilities:
  - Watch the inference-market program for new open jobs matching our model
  - Claim jobs, submit results, and collect payment
  - Register/update the node in the compute-registry
  - Heartbeat to keep the DHT registration alive
"""

import asyncio
import hashlib
import logging
import time
from dataclasses import dataclass
from pathlib import Path

try:
    from anchorpy import Program, Provider, Wallet
    from solana.rpc.async_api import AsyncClient
    from solders.keypair import Keypair
    from solders.pubkey import Pubkey

    SOLANA_AVAILABLE = True
except ImportError:
    SOLANA_AVAILABLE = False

logger = logging.getLogger(__name__)

# ─────────────────────────── exceptions ────────────────────────────────────


class BlockchainError(RuntimeError):
    """Raised when an RPC call or on-chain instruction fails."""


class InsufficientFundsError(BlockchainError):
    """Raised when the requested withdrawal amount exceeds available earnings."""


class ProposalNotFoundError(BlockchainError):
    """Raised when the given proposal ID does not exist on-chain."""


class AlreadyVotedError(BlockchainError):
    """Raised when the node wallet has already cast a vote on this proposal."""


@dataclass
class OpenJob:
    job_id: int
    client: str
    model_id: bytes
    prompt_hash: bytes
    prompt_cid: str  # IPFS CID of the encrypted prompt blob
    max_tokens: int
    payment_amount: int
    deadline: int
    job_pda: str


class BlockchainClient:
    def __init__(self, config):
        if not SOLANA_AVAILABLE:
            raise RuntimeError(
                "Solana packages not installed. Run: pip install anchorpy solders solana"
            )
        self.config = config
        self._client: AsyncClient | None = None
        self._wallet: Wallet | None = None
        self._inference_program: Program | None = None
        self._registry_program: Program | None = None

    async def connect(self) -> None:
        keypair = Keypair.from_json(Path(self.config.wallet_path).read_text())
        self._wallet = Wallet(keypair)
        self._client = AsyncClient(self.config.rpc_url)

        provider = Provider(self._client, self._wallet)

        # Load Anchor IDLs (generated by `anchor build`)
        idl_dir = Path(__file__).parent.parent / "target" / "idl"
        if idl_dir.exists():
            self._inference_program = await Program.at(
                Pubkey.from_string(self.config.inference_market_program),
                provider,
            )
            self._registry_program = await Program.at(
                Pubkey.from_string(self.config.compute_registry_program),
                provider,
            )

        logger.info("Connected to Solana RPC: %s", self.config.rpc_url)
        logger.info("Node wallet: %s", keypair.pubkey())
        logger.info("inference-market program: %s", self.config.inference_market_program)
        logger.info("compute-registry program: %s", self.config.compute_registry_program)

    async def fetch_open_jobs(self, model_id: bytes) -> list[OpenJob]:
        """
        Poll the inference-market for open jobs matching our model.
        Uses getProgramAccounts with a discriminator + model_id filter.
        """
        if not self._inference_program:
            return []

        try:
            jobs = await self._inference_program.account["Job"].all(
                filters=[
                    # status == Open (discriminator byte 0)
                    {"memcmp": {"offset": 8 + 8 + 32 + 32 + 32 + 32, "bytes": "1"}},
                ]
            )
            return [
                OpenJob(
                    job_id=j.account.id,
                    client=str(j.account.client),
                    model_id=bytes(j.account.model_id),
                    prompt_hash=bytes(j.account.prompt_hash),
                    prompt_cid=j.account.prompt_cid,
                    max_tokens=j.account.max_tokens,
                    payment_amount=j.account.payment_amount,
                    deadline=j.account.deadline,
                    job_pda=str(j.public_key),
                )
                for j in jobs
                if bytes(j.account.model_id) == model_id
            ]
        except Exception as exc:
            logger.warning("Failed to fetch open jobs: %s", exc)
            return []

    async def claim_job(self, job: OpenJob) -> bool:
        """Send the claim_job transaction to the inference-market program."""
        if not self._inference_program:
            return False
        try:
            await self._inference_program.rpc["claim_job"](
                ctx=self._inference_program.context(
                    accounts={
                        "job": Pubkey.from_string(job.job_pda),
                        "node": self._wallet.public_key,
                    }
                )
            )
            logger.info("Claimed job %d", job.job_id)
            return True
        except Exception as exc:
            logger.warning("Failed to claim job %d: %s", job.job_id, exc)
            return False

    async def submit_result(self, job: OpenJob, result_bytes: bytes, result_cid: str) -> bool:
        """Hash the result and submit it on-chain."""
        if not self._inference_program:
            return False

        result_hash = list(hashlib.sha256(result_bytes).digest())

        try:
            await self._inference_program.rpc["submit_result"](
                result_hash,
                result_cid,
                ctx=self._inference_program.context(
                    accounts={
                        "job": Pubkey.from_string(job.job_pda),
                        "node": self._wallet.public_key,
                    }
                ),
            )
            logger.info("Submitted result for job %d (CID: %s)", job.job_id, result_cid)
            return True
        except Exception as exc:
            logger.error("Failed to submit result for job %d: %s", job.job_id, exc)
            return False

    async def register_node(
        self,
        endpoint: str,
        vram_gb: int,
        gpu_count: int,
        model_ids: list[bytes],
        stake_amount: int,
    ) -> bool:
        """Register or re-register this node in the compute-registry."""
        if not self._registry_program:
            return False
        try:
            await self._registry_program.rpc["register_node"](
                endpoint,
                vram_gb,
                gpu_count,
                [[int(b) for b in mid] for mid in model_ids],
                stake_amount,
                ctx=self._registry_program.context(accounts={"operator": self._wallet.public_key}),
            )
            logger.info("Registered node in compute-registry")
            return True
        except Exception as exc:
            logger.warning("Node registration failed (may already be registered): %s", exc)
            return False

    async def heartbeat(self, endpoint: str) -> bool:
        """
        Update the node's endpoint in the compute-registry to signal liveness.

        Called every ~60 seconds by the node server. Allows detection of IP
        changes on GPU rental platforms (Vast.ai reassigns IPs on restart).
        """
        if not self._registry_program:
            return False
        try:
            await self._registry_program.rpc["update_endpoint"](
                endpoint,
                ctx=self._registry_program.context(accounts={"operator": self._wallet.public_key}),
            )
            logger.debug("Heartbeat: updated endpoint to %s", endpoint)
            return True
        except Exception as exc:
            logger.warning("Heartbeat failed: %s", exc)
            return False

    async def auto_settle_expired_jobs(self) -> int:
        """
        Permissionlessly settle any inference jobs whose challenge windows
        have closed. Anyone can call auto_settle — no special authority needed.

        Returns the number of jobs settled.
        """
        if not self._inference_program:
            return 0

        settled = 0
        try:
            now = int(time.time())
            jobs = await self._inference_program.account["Job"].all()
            for j in jobs:
                status = str(j.account.status)
                if "PendingAcceptance" in status and j.account.claimed_at + 300 < now:
                    try:
                        await self._inference_program.rpc["auto_settle"](
                            ctx=self._inference_program.context(accounts={"job": j.public_key})
                        )
                        settled += 1
                        logger.info("Auto-settled job %d", j.account.id)
                    except Exception:
                        pass
        except Exception as exc:
            logger.warning("auto_settle scan failed: %s", exc)

        return settled

    async def watch_for_challenges(self, job_id: int) -> bool:
        """
        Poll the on-chain job account for up to 5 minutes watching for a status
        change to "Disputed".

        Returns True if the job was challenged within the window, False if the
        challenge window passed without a dispute.

        This is a placeholder that wraps the on-chain dispute logic already
        implemented in the Rust inference-market program.
        """
        if not self._inference_program:
            return False

        challenge_window_seconds = 300  # matches CHALLENGE_WINDOW_SECONDS in Rust
        poll_interval = 5.0
        deadline = time.monotonic() + challenge_window_seconds

        while time.monotonic() < deadline:
            try:
                seeds = [b"job", job_id.to_bytes(8, "little")]
                job_pda, _ = Pubkey.find_program_address(
                    seeds,
                    Pubkey.from_string(self.config.inference_market_program),
                )
                account = await self._inference_program.account["Job"].fetch(job_pda)
                status = str(account.status)
                if "Disputed" in status:
                    logger.info("Job %d was challenged (status: Disputed)", job_id)
                    return True
                if "Completed" in status or "Refunded" in status:
                    # Settled without dispute
                    return False
            except Exception as exc:
                logger.warning("watch_for_challenges: failed to fetch job %d: %s", job_id, exc)
            await asyncio.sleep(poll_interval)

        logger.info("Job %d: challenge window closed without dispute", job_id)
        return False

    async def get_wallet_balance(self) -> float:
        """Return the wallet's SOL balance as a float (in SOL, not lamports)."""
        if not self._client or not self._wallet:
            return 0.0
        try:
            resp = await self._client.get_balance(self._wallet.public_key)
            lamports = resp.value
            sol = lamports / 1_000_000_000
            logger.debug("Wallet balance: %.4f SOL (%d lamports)", sol, lamports)
            return sol
        except Exception as exc:
            logger.warning("Failed to fetch wallet balance: %s", exc)
            return 0.0

    async def request_airdrop(self, amount_lamports: int = 1_000_000_000) -> bool:
        """
        Request an airdrop on devnet/testnet. No-op on mainnet.

        Args:
            amount_lamports: Amount to airdrop in lamports (default 1 SOL).

        Returns:
            True if the airdrop was requested successfully, False otherwise.
        """
        if not self._client or not self._wallet:
            return False

        rpc_url = self.config.rpc_url
        if "mainnet" in rpc_url:
            logger.warning("request_airdrop called on mainnet — skipping")
            return False

        try:
            resp = await self._client.request_airdrop(self._wallet.public_key, amount_lamports)
            logger.info(
                "Airdrop of %d lamports requested, tx: %s",
                amount_lamports,
                resp.value,
            )
            return True
        except Exception as exc:
            logger.warning("Airdrop request failed: %s", exc)
            return False

    # ─────────────────────────── earnings / withdraw ───────────────────────

    async def get_earnings(self) -> dict:
        """
        Fetch the node's earnings data from the compute-registry PDA.

        Returns a dict with keys:
          - available_lamports  : claimable now (staked_amount stored in NodeRecord)
          - total_earned_lamports : cumulative earnings derived from jobs_completed
          - pending_lamports    : in-flight jobs not yet settled (reported as 0 here
                                  because the on-chain record has no such field)
        """
        if not self._registry_program or not self._wallet:
            raise BlockchainError("Not connected – call connect() first")

        try:
            node_pda, _ = Pubkey.find_program_address(
                [b"node", bytes(self._wallet.public_key)],
                self._registry_program.program_id,
            )
            record = await self._registry_program.account["NodeRecord"].fetch(node_pda)
            # earnings_claimable is represented by the staked_amount available
            # and total earned is proxied by jobs_completed (no per-job amount here)
            available = int(record.staked_amount)
            jobs = max(int(record.jobs_completed), 1)
            total_earned = int(record.jobs_completed) * available // jobs
            return {
                "available_lamports": available,
                "total_earned_lamports": total_earned,
                "pending_lamports": 0,
            }
        except BlockchainError:
            raise
        except Exception as exc:
            raise BlockchainError(f"Failed to fetch earnings: {exc}") from exc

    async def withdraw_earnings(self, amount_lamports: int | None = None) -> dict:
        """
        Withdraw earned SOL to the node wallet via the inference-market program's
        ``withdraw`` instruction.

        Args:
            amount_lamports: Exact amount to withdraw (in lamports).  Pass ``None``
                to withdraw the entire available balance.

        Returns:
            {
                "tx_signature": str,
                "amount_sol": float,
                "new_balance_sol": float,
            }

        Raises:
            InsufficientFundsError: if amount_lamports exceeds the available balance.
            BlockchainError: on any RPC / program error.
        """
        if not self._inference_program or not self._wallet:
            raise BlockchainError("Not connected – call connect() first")

        # Fetch current earnings to validate the requested amount
        earnings = await self.get_earnings()
        available = earnings["available_lamports"]

        if amount_lamports is None:
            amount_lamports = available

        if amount_lamports > available:
            raise InsufficientFundsError(
                f"Requested {amount_lamports} lamports but only {available} available"
            )

        try:
            node_pda, _ = Pubkey.find_program_address(
                [b"node", bytes(self._wallet.public_key)],
                self._inference_program.program_id,
            )
            tx_sig = await self._inference_program.rpc["withdraw"](
                amount_lamports,
                ctx=self._inference_program.context(
                    accounts={
                        "node": node_pda,
                        "operator": self._wallet.public_key,
                    }
                ),
            )
        except BlockchainError:
            raise
        except Exception as exc:
            raise BlockchainError(f"Withdraw instruction failed: {exc}") from exc

        new_balance_sol = await self.get_wallet_balance()
        amount_sol = amount_lamports / 1_000_000_000

        logger.info(
            "Withdrew %.6f SOL (tx: %s); new balance: %.6f SOL",
            amount_sol,
            tx_sig,
            new_balance_sol,
        )
        return {
            "tx_signature": str(tx_sig),
            "amount_sol": amount_sol,
            "new_balance_sol": new_balance_sol,
        }

    # ─────────────────────────── governance ────────────────────────────────

    async def get_governance_proposals(self) -> list[dict]:
        """
        Fetch all Proposal PDAs from the governance program.

        Returns a list of dicts with keys:
          id, title, description, yes_votes, no_votes, status, ends_at
        """
        if not self._wallet:
            raise BlockchainError("Not connected – call connect() first")

        governance_program_id = getattr(
            self.config, "governance_program", "3CvE7tX9rMwPfBgY2nKjH6oL4sQ8uZaD5mR1iW0eN9T"
        )

        try:
            from anchorpy import Provider

            provider = Provider(self._client, self._wallet)
            gov_program = await Program.at(
                Pubkey.from_string(governance_program_id),
                provider,
            )
            proposals_raw = await gov_program.account["Proposal"].all()
        except BlockchainError:
            raise
        except Exception as exc:
            raise BlockchainError(f"Failed to fetch governance proposals: {exc}") from exc

        proposals = []
        for p in proposals_raw:
            acc = p.account
            proposals.append(
                {
                    "id": int(acc.id),
                    "title": str(acc.title),
                    "description": str(acc.description_cid),
                    "yes_votes": int(acc.votes_for),
                    "no_votes": int(acc.votes_against),
                    "status": str(acc.status),
                    "ends_at": int(acc.voting_ends_at),
                }
            )
        proposals.sort(key=lambda x: x["id"])
        return proposals

    async def cast_governance_vote(self, proposal_id: int, vote: bool) -> str:
        """
        Cast a yes/no vote on a governance proposal.

        Args:
            proposal_id: Integer ID of the proposal.
            vote: True = For, False = Against.

        Returns:
            Transaction signature string.

        Raises:
            ProposalNotFoundError: if no proposal with that ID exists.
            AlreadyVotedError: if this wallet has already voted on the proposal.
            BlockchainError: on any other RPC failure.
        """
        if not self._wallet:
            raise BlockchainError("Not connected – call connect() first")

        governance_program_id = getattr(
            self.config, "governance_program", "3CvE7tX9rMwPfBgY2nKjH6oL4sQ8uZaD5mR1iW0eN9T"
        )

        try:
            from anchorpy import Provider

            provider = Provider(self._client, self._wallet)
            gov_program = await Program.at(
                Pubkey.from_string(governance_program_id),
                provider,
            )
        except Exception as exc:
            raise BlockchainError(f"Failed to load governance program: {exc}") from exc

        # Derive proposal PDA and verify it exists
        try:
            proposal_pda, _ = Pubkey.find_program_address(
                [b"proposal", proposal_id.to_bytes(8, "little")],
                gov_program.program_id,
            )
            await gov_program.account["Proposal"].fetch(proposal_pda)
        except BlockchainError:
            raise
        except Exception as exc:
            raise ProposalNotFoundError(f"Proposal {proposal_id} not found: {exc}") from exc

        # Check if the vote record already exists for this voter
        try:
            vote_record_pda, _ = Pubkey.find_program_address(
                [
                    b"vote",
                    bytes(self._wallet.public_key),
                    proposal_id.to_bytes(8, "little"),
                ],
                gov_program.program_id,
            )
            vote_record = await gov_program.account["VoteRecord"].fetch(vote_record_pda)
            if vote_record.has_voted:
                raise AlreadyVotedError(f"Already voted on proposal {proposal_id}")
        except (ProposalNotFoundError, AlreadyVotedError):
            raise
        except Exception:
            # VoteRecord doesn't exist yet – this is the first vote, proceed
            pass

        # Build the VoteChoice enum value expected by the Anchor program
        # VoteChoice: For = 0, Against = 1, Abstain = 2 (from governance/src/lib.rs)
        vote_choice = {"For": {}} if vote else {"Against": {}}

        try:
            tx_sig = await gov_program.rpc["cast_vote"](
                vote_choice,
                ctx=gov_program.context(
                    accounts={
                        "proposal": proposal_pda,
                        "vote_record": vote_record_pda,
                        "voter": self._wallet.public_key,
                    }
                ),
            )
        except BlockchainError:
            raise
        except AlreadyVotedError:
            raise
        except Exception as exc:
            err_str = str(exc).lower()
            if "already voted" in err_str or "alreadyvoted" in err_str:
                raise AlreadyVotedError(f"Already voted on proposal {proposal_id}") from exc
            raise BlockchainError(f"cast_vote instruction failed: {exc}") from exc

        logger.info(
            "Voted %s on proposal %d (tx: %s)",
            "For" if vote else "Against",
            proposal_id,
            tx_sig,
        )
        return str(tx_sig)

    async def close(self) -> None:
        if self._client:
            await self._client.close()
