"""
Solana interaction layer for compute nodes.

Responsibilities:
  - Watch the inference-market program for new open jobs matching our model
  - Claim jobs, submit results, and collect payment
  - Register/update the node in the compute-registry
  - Heartbeat to keep the DHT registration alive
"""

import hashlib
import logging
from dataclasses import dataclass
from pathlib import Path

try:
    from anchorpy import Program, Provider, Wallet
    from solana.rpc.async_api import AsyncClient
    from solders.keypair import Keypair
    from solders.pubkey import Pubkey

    SOLANA_AVAILABLE = True
except ImportError:
    SOLANA_AVAILABLE = False

logger = logging.getLogger(__name__)


@dataclass
class OpenJob:
    job_id: int
    client: str
    model_id: bytes
    prompt_hash: bytes
    max_tokens: int
    payment_amount: int
    deadline: int
    job_pda: str


class BlockchainClient:
    def __init__(self, config):
        if not SOLANA_AVAILABLE:
            raise RuntimeError(
                "Solana packages not installed. Run: pip install anchorpy solders solana"
            )
        self.config = config
        self._client: AsyncClient | None = None
        self._wallet: Wallet | None = None
        self._inference_program: Program | None = None
        self._registry_program: Program | None = None

    async def connect(self) -> None:
        keypair = Keypair.from_json(Path(self.config.wallet_path).read_text())
        self._wallet = Wallet(keypair)
        self._client = AsyncClient(self.config.rpc_url)

        provider = Provider(self._client, self._wallet)

        # Load Anchor IDLs (generated by `anchor build`)
        idl_dir = Path(__file__).parent.parent / "target" / "idl"
        if idl_dir.exists():
            self._inference_program = await Program.at(
                Pubkey.from_string(self.config.inference_market_program),
                provider,
            )
            self._registry_program = await Program.at(
                Pubkey.from_string(self.config.compute_registry_program),
                provider,
            )

        logger.info("Connected to Solana RPC: %s", self.config.rpc_url)
        logger.info("Node wallet: %s", keypair.pubkey())

    async def fetch_open_jobs(self, model_id: bytes) -> list[OpenJob]:
        """
        Poll the inference-market for open jobs matching our model.
        Uses getProgramAccounts with a discriminator + model_id filter.
        """
        if not self._inference_program:
            return []

        try:
            jobs = await self._inference_program.account["Job"].all(
                filters=[
                    # status == Open (discriminator byte 0)
                    {"memcmp": {"offset": 8 + 8 + 32 + 32 + 32 + 32, "bytes": "1"}},
                ]
            )
            return [
                OpenJob(
                    job_id=j.account.id,
                    client=str(j.account.client),
                    model_id=bytes(j.account.model_id),
                    prompt_hash=bytes(j.account.prompt_hash),
                    max_tokens=j.account.max_tokens,
                    payment_amount=j.account.payment_amount,
                    deadline=j.account.deadline,
                    job_pda=str(j.public_key),
                )
                for j in jobs
                if bytes(j.account.model_id) == model_id
            ]
        except Exception as exc:
            logger.warning("Failed to fetch open jobs: %s", exc)
            return []

    async def claim_job(self, job: OpenJob) -> bool:
        """Send the claim_job transaction to the inference-market program."""
        if not self._inference_program:
            return False
        try:
            await self._inference_program.rpc["claim_job"](
                ctx=self._inference_program.context(
                    accounts={
                        "job": Pubkey.from_string(job.job_pda),
                        "node": self._wallet.public_key,
                    }
                )
            )
            logger.info("Claimed job %d", job.job_id)
            return True
        except Exception as exc:
            logger.warning("Failed to claim job %d: %s", job.job_id, exc)
            return False

    async def submit_result(self, job: OpenJob, result_bytes: bytes, result_cid: str) -> bool:
        """Hash the result and submit it on-chain."""
        if not self._inference_program:
            return False

        result_hash = list(hashlib.sha256(result_bytes).digest())

        try:
            await self._inference_program.rpc["submit_result"](
                result_hash,
                result_cid,
                ctx=self._inference_program.context(
                    accounts={
                        "job": Pubkey.from_string(job.job_pda),
                        "node": self._wallet.public_key,
                    }
                ),
            )
            logger.info("Submitted result for job %d (CID: %s)", job.job_id, result_cid)
            return True
        except Exception as exc:
            logger.error("Failed to submit result for job %d: %s", job.job_id, exc)
            return False

    async def register_node(
        self,
        endpoint: str,
        vram_gb: int,
        gpu_count: int,
        model_ids: list[bytes],
        stake_amount: int,
    ) -> bool:
        """Register or re-register this node in the compute-registry."""
        if not self._registry_program:
            return False
        try:
            await self._registry_program.rpc["register_node"](
                endpoint,
                vram_gb,
                gpu_count,
                [[int(b) for b in mid] for mid in model_ids],
                stake_amount,
                ctx=self._registry_program.context(accounts={"operator": self._wallet.public_key}),
            )
            logger.info("Registered node in compute-registry")
            return True
        except Exception as exc:
            logger.warning("Node registration failed (may already be registered): %s", exc)
            return False

    async def close(self) -> None:
        if self._client:
            await self._client.close()
