"""
Solana interaction layer for compute nodes.

Responsibilities:
  - Watch the inference-market program for new open jobs matching our model
  - Claim jobs, submit results, and collect payment
  - Register/update the node in the compute-registry
  - Heartbeat to keep the DHT registration alive
"""

import asyncio
import hashlib
import logging
from dataclasses import dataclass
from pathlib import Path

try:
    from anchorpy import Program, Provider, Wallet
    from solana.rpc.async_api import AsyncClient
    from solders.keypair import Keypair
    from solders.pubkey import Pubkey

    SOLANA_AVAILABLE = True
except ImportError:
    SOLANA_AVAILABLE = False

logger = logging.getLogger(__name__)


@dataclass
class OpenJob:
    job_id: int
    client: str
    model_id: bytes
    prompt_hash: bytes
    prompt_cid: str  # IPFS CID of the encrypted prompt blob
    max_tokens: int
    payment_amount: int
    deadline: int
    job_pda: str


class BlockchainClient:
    def __init__(self, config):
        if not SOLANA_AVAILABLE:
            raise RuntimeError(
                "Solana packages not installed. Run: pip install anchorpy solders solana"
            )
        self.config = config
        self._client: AsyncClient | None = None
        self._wallet: Wallet | None = None
        self._inference_program: Program | None = None
        self._registry_program: Program | None = None

    async def connect(self) -> None:
        keypair = Keypair.from_json(Path(self.config.wallet_path).read_text())
        self._wallet = Wallet(keypair)
        self._client = AsyncClient(self.config.rpc_url)

        provider = Provider(self._client, self._wallet)

        # Load Anchor IDLs (generated by `anchor build`)
        idl_dir = Path(__file__).parent.parent / "target" / "idl"
        if idl_dir.exists():
            self._inference_program = await Program.at(
                Pubkey.from_string(self.config.inference_market_program),
                provider,
            )
            self._registry_program = await Program.at(
                Pubkey.from_string(self.config.compute_registry_program),
                provider,
            )

        logger.info("Connected to Solana RPC: %s", self.config.rpc_url)
        logger.info("Node wallet: %s", keypair.pubkey())

    async def fetch_open_jobs(self, model_id: bytes) -> list[OpenJob]:
        """
        Poll the inference-market for open jobs matching our model.
        Uses getProgramAccounts with a discriminator + model_id filter.
        """
        if not self._inference_program:
            return []

        try:
            jobs = await self._inference_program.account["Job"].all(
                filters=[
                    # status == Open (discriminator byte 0)
                    {"memcmp": {"offset": 8 + 8 + 32 + 32 + 32 + 32, "bytes": "1"}},
                ]
            )
            return [
                OpenJob(
                    job_id=j.account.id,
                    client=str(j.account.client),
                    model_id=bytes(j.account.model_id),
                    prompt_hash=bytes(j.account.prompt_hash),
                    prompt_cid=j.account.prompt_cid,
                    max_tokens=j.account.max_tokens,
                    payment_amount=j.account.payment_amount,
                    deadline=j.account.deadline,
                    job_pda=str(j.public_key),
                )
                for j in jobs
                if bytes(j.account.model_id) == model_id
            ]
        except Exception as exc:
            logger.warning("Failed to fetch open jobs: %s", exc)
            return []

    async def claim_job(self, job: OpenJob) -> bool:
        """Send the claim_job transaction to the inference-market program."""
        if not self._inference_program:
            return False
        try:
            await self._inference_program.rpc["claim_job"](
                ctx=self._inference_program.context(
                    accounts={
                        "job": Pubkey.from_string(job.job_pda),
                        "node": self._wallet.public_key,
                    }
                )
            )
            logger.info("Claimed job %d", job.job_id)
            return True
        except Exception as exc:
            logger.warning("Failed to claim job %d: %s", job.job_id, exc)
            return False

    async def submit_result(self, job: OpenJob, result_bytes: bytes, result_cid: str) -> bool:
        """Hash the result and submit it on-chain."""
        if not self._inference_program:
            return False

        result_hash = list(hashlib.sha256(result_bytes).digest())

        try:
            await self._inference_program.rpc["submit_result"](
                result_hash,
                result_cid,
                ctx=self._inference_program.context(
                    accounts={
                        "job": Pubkey.from_string(job.job_pda),
                        "node": self._wallet.public_key,
                    }
                ),
            )
            logger.info("Submitted result for job %d (CID: %s)", job.job_id, result_cid)
            return True
        except Exception as exc:
            logger.error("Failed to submit result for job %d: %s", job.job_id, exc)
            return False

    async def register_node(
        self,
        endpoint: str,
        vram_gb: int,
        gpu_count: int,
        model_ids: list[bytes],
        stake_amount: int,
    ) -> bool:
        """Register or re-register this node in the compute-registry."""
        if not self._registry_program:
            return False
        try:
            await self._registry_program.rpc["register_node"](
                endpoint,
                vram_gb,
                gpu_count,
                [[int(b) for b in mid] for mid in model_ids],
                stake_amount,
                ctx=self._registry_program.context(accounts={"operator": self._wallet.public_key}),
            )
            logger.info("Registered node in compute-registry")
            return True
        except Exception as exc:
            logger.warning("Node registration failed (may already be registered): %s", exc)
            return False

    async def heartbeat(self, endpoint: str) -> bool:
        """
        Update the node's endpoint in the compute-registry to signal liveness.

        Called every ~60 seconds by the node server. Allows detection of IP
        changes on GPU rental platforms (Vast.ai reassigns IPs on restart).
        """
        if not self._registry_program:
            return False
        try:
            await self._registry_program.rpc["update_endpoint"](
                endpoint,
                ctx=self._registry_program.context(accounts={"operator": self._wallet.public_key}),
            )
            logger.debug("Heartbeat: updated endpoint to %s", endpoint)
            return True
        except Exception as exc:
            logger.warning("Heartbeat failed: %s", exc)
            return False

    async def auto_settle_expired_jobs(self) -> int:
        """
        Permissionlessly settle any inference jobs whose challenge windows
        have closed. Anyone can call auto_settle — no special authority needed.

        Returns the number of jobs settled.
        """
        if not self._inference_program:
            return 0

        settled = 0
        try:
            import time

            now = int(time.time())
            jobs = await self._inference_program.account["Job"].all()
            for j in jobs:
                status = str(j.account.status)
                if "PendingAcceptance" in status and j.account.claimed_at + 300 < now:
                    try:
                        await self._inference_program.rpc["auto_settle"](
                            ctx=self._inference_program.context(accounts={"job": j.public_key})
                        )
                        settled += 1
                        logger.info("Auto-settled job %d", j.account.id)
                    except Exception:
                        pass
        except Exception as exc:
            logger.warning("auto_settle scan failed: %s", exc)

        return settled

    async def watch_for_challenges(self, job_id: int) -> bool:
        """
        Poll the on-chain job account for up to 5 minutes watching for a status
        change to "Disputed".

        Returns True if the job was challenged within the window, False if the
        challenge window passed without a dispute.

        This is a placeholder that wraps the on-chain dispute logic already
        implemented in the Rust inference-market program.
        """
        if not self._inference_program:
            return False

        import time

        challenge_window_seconds = 300  # matches CHALLENGE_WINDOW_SECONDS in Rust
        poll_interval = 5.0
        deadline = time.monotonic() + challenge_window_seconds

        while time.monotonic() < deadline:
            try:
                from solders.pubkey import Pubkey

                seeds = [b"job", job_id.to_bytes(8, "little")]
                job_pda, _ = Pubkey.find_program_address(
                    seeds,
                    Pubkey.from_string(self.config.inference_market_program),
                )
                account = await self._inference_program.account["Job"].fetch(job_pda)
                status = str(account.status)
                if "Disputed" in status:
                    logger.info("Job %d was challenged (status: Disputed)", job_id)
                    return True
                if "Completed" in status or "Refunded" in status:
                    # Settled without dispute
                    return False
            except Exception as exc:
                logger.warning("watch_for_challenges: failed to fetch job %d: %s", job_id, exc)
            await __import__("asyncio").sleep(poll_interval)

        logger.info("Job %d: challenge window closed without dispute", job_id)
        return False

    async def close(self) -> None:
        if self._client:
            await self._client.close()
