#!/usr/bin/env python3
"""
Initialize the inference market and compute registry on Solana devnet.

Usage:
    python scripts/init_devnet.py --rpc https://api.devnet.solana.com \\
        --wallet ~/.config/solana/id.json \\
        --market-program 5YQyZqXkJHy6V3JMxKqXyLqfP9V2A3j8Rk7mN4oD1eW \\
        --registry-program 8KpR2mT6uLqVwNzS4eBfY9oA3cJ7iGxH1nD5sW0qF2M
"""

import argparse
import sys
from pathlib import Path


def parse_args():
    p = argparse.ArgumentParser(description="Initialize devnet programs")
    p.add_argument("--rpc", default="https://api.devnet.solana.com")
    p.add_argument("--wallet", default=str(Path.home() / ".config/solana/id.json"))
    p.add_argument("--market-program", default="5YQyZqXkJHy6V3JMxKqXyLqfP9V2A3j8Rk7mN4oD1eW")
    p.add_argument("--registry-program", default="8KpR2mT6uLqVwNzS4eBfY9oA3cJ7iGxH1nD5sW0qF2M")
    p.add_argument("--governance-program", default="3CvE7tX9rMwPfBgY2nKjH6oL4sQ8uZaD5mR1iW0eN9T")
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would happen without sending transactions",
    )
    return p.parse_args()


def main():
    args = parse_args()

    print(f"RPC: {args.rpc}")
    print(f"Wallet: {args.wallet}")
    print()

    try:
        from anchorpy import Program, Provider, Wallet  # noqa: F401
        from solana.rpc.api import Client
        from solders.keypair import Keypair
        from solders.pubkey import Pubkey  # noqa: F401
    except ImportError:
        print("ERROR: Solana packages not installed.")
        print("Run: pip install anchorpy solana solders")
        sys.exit(1)

    wallet_kp = Keypair.from_json(Path(args.wallet).read_text())
    print(f"Wallet pubkey: {wallet_kp.pubkey()}")

    client = Client(args.rpc)
    balance = client.get_balance(wallet_kp.pubkey()).value
    print(f"Balance: {balance / 1e9:.4f} SOL")

    if balance < 1_000_000_000:  # < 1 SOL
        print("WARNING: Low balance. You may need to airdrop SOL for devnet.")
        print(f"  solana airdrop 2 {wallet_kp.pubkey()} --url {args.rpc}")

    if args.dry_run:
        print("\n[DRY RUN] Would initialize:")
        print(f"  - inference-market at {args.market_program}")
        print(f"  - compute-registry at {args.registry_program}")
        print(f"  - governance at {args.governance_program}")
        return

    print("\nTo initialize, run the Anchor typescript client or use the IDL directly.")
    print("See: scripts/ts/init_market.ts (to be generated by `anchor idl init`)")


if __name__ == "__main__":
    main()
